name: Deployment Workflow

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "UNLICENSE"
      - ".dockerignore"
      - ".gitignore"
      - ".editorconfig"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/madetara/tforward/bot:0.1.${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_image:
    runs-on: ubuntu-22.04
    needs: build_and_push
    env:
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      BOT_URL: ${{ secrets.BOT_URL }}
      BOT_PORT: ${{ secrets.BOT_PORT }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      UPTRACE_DSN: ${{ secrets.UPTRACE_DSN }}
      CR_PAT: ${{ secrets.CR_PAT }}
    steps:
      - name: Deploy image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: root
          envs: TG_TOKEN, BOT_URL, BOT_PORT, CHANNEL_ID, UPTRACE_DSN, CR_PAT, GITHUB_RUN_NUMBER
          script: |
            echo $CR_PAT | docker login ghcr.io -u madetara --password-stdin
            docker stop tforward
            docker rm tforward
            docker run -d --name tforward --restart unless-stopped -p $BOT_PORT:3002 \
              --env TG_TOKEN="$TG_TOKEN" \
              --env BOT_URL="$BOT_URL" \
              --env BOT_PORT="$BOT_PORT" \
              --env CHANNEL_ID="$CHANNEL_ID" \
              --env UPTRACE_DSN="$UPTRACE_DSN" \
              -v "/root/workload/tforward:/data" \
              "ghcr.io/madetara/tforward/bot:0.1.$GITHUB_RUN_NUMBER"
